### ISSUE TITLE
A lot of "Powered By Flask" websites were deprecated

### ISSUE THREAD

**Issue by hbrls** [pallets/flask-website#10]
Do we need a clean up?

I'll +1 if you'd like to keep the ones that WAS powered by Flask once upon a time. But I will not accept one like this [http://meetupmeeter.com/](http://meetupmeeter.com/), whose footer says `Proudly powered by WordPress`.

And this one [http://rydehhffps.org.au/](http://rydehhffps.org.au/). `Powered by Webpedia`

**Comment by remram44** [comment]
Went through the "websites" list.

No evidence of Flask:
- [einfachjabber.de](http://einfachjabber.de/)
- [jonathanstreet.com](http://jonathanstreet.com/)
- [mediaqueri.es](http://mediaqueri.es/)
- [community.nuxeo.com](http://community.nuxeo.com/)
- [redbankcreative.org](http://www.redbankcreative.org/)
- [robinverton.de](http://robinverton.de/)
- [rockyou.fm](https://www.rockyou.fm/)
- [weluse.de](http://weluse.de/)
- [ymasuda.jp](http://ymasuda.jp/)

NOT flask:
- [rydehhffps.org.au](http://rydehhffps.org.au/) ("powered by [Webpedia](http://www.webpedia.com.au/)")

Offline:
- [feedback.flask.pocoo.org](http://feedback.flask.pocoo.org/) (NXDOMAIN) <- that's yours @mitsuhiko, right?
- [getpython3.net](http://getpython3.net/) (NXDOMAIN)
- [learnbuffett.com](http://www.learnbuffett.com/) (SERVFAIL from most locations)
- [ListaPrive](http://www.listaprive.com/) (SERVFAIL)
- [meetupmeeter.com](http://meetupmeeter.com/) (URL serves dominiquerollins.com instead -- vhost fail)
- [pizje.ns-keip.ru](http://pizje.ns-keip.ru/) (timeout)
- [punchfork.com](http://punchfork.com/) (still has an explanation page stating what it was about)
- [pycon.disqus.com](https://pycon.disqus.com/) (redirects to /admin/moderate/ then 403)
- [pythondojoe.appspot.com](http://pythondojoe.appspot.com/) (404)
- [q-financial.com](http://www.q-financial.com/) ("domain for sale")
- [new.rdrei.net](http://new.rdrei.net/) (NXDOMAIN)
- [steyr-touristik.at/](http://www.steyr-touristik.at/) (redirects to a phpMyAdmin)
- [wasitup.com](http://wasitup.com/) (still has an explanation page)

Sourcecode link dead:
- [community.nuxeo.com - github](https://github.com/sfermigier/nuxeo.org)

**Comment by davidism** [comment]
b3766e9d370d6666bbe5d2795bf0301335e8a740 I removed anything that 404's, looks like it was taken over (spam), or doesn't have evidence of Flask.

54ae20ef03075a128c5cc173ae205e59b8daac20 To balance that out, I added an active project. :-)

**Comment by remram44** [comment]
When does the website refresh? Neither this nor #23 seem to appear online?

**Comment by davidism** [comment]
A new build would need to be pushed to the server.  I don't control that.
