### ISSUE TITLE
404 link at Snippet 89

### ISSUE THREAD

**Issue by luciomartinez** [pallets/flask-website#15]
At the [Snippet 89](http://flask.pocoo.org/snippets/89/) there is a link pointing to _Localtunnel_ website. Unfortunelly, Localtunnel home page has changed from http://progrium.com/localtunnel/ to http://localtunnel.me/

**Comment by davidism** [comment]
Fixed it. Just note that the entire snippets library is unofficial and unmaintained. It will be frozen with a big warning at the top soon.
