### ISSUE TITLE
http://flask.pocoo.org/docs/flask-docs.pdf shows error 

### ISSUE THREAD

**Issue by auvipy** [pallets/flask-website#16]

**Comment by cldershem** [comment]
This is a duplicate of #17.

**Comment by davidism** [comment]
See mitsuhiko/flask-sqlalchemy#209, the docs are built but not moved to the expected location on the server.  http://flask.pocoo.org/docs/0.10/.latex/Flask.pdf

Fixed in 763ddeb2ac1d3478c1262e51b7c729ac3817b0f4

**Comment by zlolik** [comment]
Again 404
