### ISSUE TITLE
SQLAlchemy Declarative extension link broken

### ISSUE THREAD

**Issue by ghost** [pallets/flask-website#21]
on page http://www.sqlalchemy.org/docs/orm/extensions/declarative.html under http://flask.pocoo.org/docs/0.10/patterns/sqlalchemy/#declarative

**Comment by cldershem** [comment]
To be fair, the link on [sqlalchemy's own site](http://docs.sqlalchemy.org/en/rel_0_8/orm/extensions/declarative.html) is broken for any version after 0.8.  It looks to me like they've restructured that section quite a bit and without reading the whole section it's hard to say what page would be the equivalent today.  My guess is the [main index](http://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/index.html) for declarative?

@andrewblaney If you can confirm that's correct or point me in the right direction, I can submit the pull request.

**Comment by davidism** [comment]
Fixed in mitsuhiko/flask#1278. This is visible on the dev docs.
