### ISSUE TITLE
i have download files and run the same file but i get an error

### ISSUE THREAD

**Issue by imdadhussain** [pallets/flask-website#22]
(flask) C:\Users\admin\Desktop\website>python run.py
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from flask_website import app
  File "C:\Users\admin\Desktop\website\flask_website__init__.py", line 35, in <
module>
    from flask_website.views import general
  File "C:\Users\admin\Desktop\website\flask_website\views\general.py", line 6,
in <module>
    from flask_website.utils import requires_login, request_wants_json
  File "C:\Users\admin\Desktop\website\flask_website\utils.py", line 2, in <modu
le>
    import creoleparser
ImportError: No module named 'creoleparser'

**Comment by cldershem** [comment]
@imdadhussain You say you downloaded the files, but don't mention install the the dependencies in `requirements.txt`.  My guess would be that you either need to install the requirements or activate a virtualenv.  If you're not familiar with either of these checkout [this guide](http://docs.python-guide.org/en/latest/dev/virtualenvs/) for a pretty decent overview.

**Comment by imdadhussain** [comment]
i have done the whole procees but still getting the same error
