### ISSUE TITLE
Some searches involving “flash” throw a 500 error

### ISSUE THREAD

**Issue by alexwlchan** [pallets/flask-website#26]
If I try to search for “flash”, I get a 500 error:

http://flask.pocoo.org/search/?q=flash

I’ve found a few other searches related to flash that seem to fail; they may or may not be related:
- Leading/trailing whitespace, e.g. [“___flash”](http://flask.pocoo.org/search/?q=+++flash) or [“flash___”](http://flask.pocoo.org/search/?q=flash+++)
- Leading/trailing words with one or three characters – “a flash”, “big flash”, “flash a” and “flash big” all fail.
- “flashe” and “flashes” both fail – appending other characters seems okay.

And some searches that work:
- Prepending characters to “flash” – so “aflash”, “abflash”, “abcflash”, and so on seem to work.
- Leading/trailing words with other numbers of characters – “hi flash”, “flash ab”, “flash abcd”, “high flash”, “highest flash” all work.

Repro’d in Safari and Chrome on OS X. I’m coming from a UK-based ISP, if that’s significant.

I was trying to search for the [pages on message flashing](http://flask.pocoo.org/docs/0.10/api/#message-flashing). I couldn’t find a pattern to rejected searches, except that they all involve the word “flash”.

**Comment by alexwlchan** [comment]
I tried cloning this repo and spinning up a local copy of the website, but I couldn’t reproduce easily – the search backend seems to be missing. None of my searches return any results.

**Comment by davidism** [comment]
3471381b5894536142a9460410e0efe5e8b1b294 I fixed an issue with the docs regex not matching when building the index.  Not sure if this is what was causing the issue though.  Will need @mitsuhiko to figure out what the server error is.

For reference, to index docs:
- clone flask next to flask-website
- run `make dirhtml` in the flask docs
- run `python update_doc_searchindex.py`

**Comment by davidism** [comment]
Some other terms that fail: nginx, sqlite, flaskr.  The only pattern I see is they are all terms that appear in subdirectories in the docs.  This doesn't fail locally though.

**Comment by davidism** [comment]
Solved by removing the search button. 0eb55a56

**Comment by mitsuhiko** [comment]
:D
