### ISSUE TITLE
Link to PDF version of docs gives a 404 error

### ISSUE THREAD

**Issue by gitasong** [pallets/flask-website#49]
The link to http://flask.pocoo.org/docs/0.12/.latex/Flask.pdf on the home page of the Flask website gives a 404 error. 

A search of this Github repo for ".pdf" yields a single search result: flask_website/static/logo/flask.pdf, which is damaged.

**Comment by davidism** [comment]
Thanks, this is reported against the docs builder repo already.

**Comment by davidism** [comment]
Duplicate of https://github.com/pocoo/flask-docs/issues/3
