### ISSUE TITLE
Broken links for example websites

### ISSUE THREAD

**Issue by OverkillGuy** [pallets/flask-website#62]
In the main website, github links for minitwit and flaskr are broken.
That's a shame because I'd love to see them.

https://github.com/pallets/flask-website/blob/09f35e60617a239be105edd353a0449406b0dab2/flask_website/templates/general/index.html#L89
https://github.com/pallets/flask-website/blob/09f35e60617a239be105edd353a0449406b0dab2/flask_website/templates/general/index.html#L91

**Comment by davidism** [comment]
pallets/flask#2676

**Comment by davidism** [comment]
These are fixed.
