### ISSUE TITLE
I cannot install Creoleparser on python 3.5

### ISSUE THREAD

**Issue by zhangsanfu** [pallets/flask-website#70]
```
> pip install creoleparser 
Looking in indexes: https://pypi.douban.com/simple/
Collecting creoleparser
Https://pypi.doubanio.com/packages/2a/0c/f442415eae7f0bb077fed28f6f8b1ddb07b32f216b2268dca9c267655f0d/Creoleparser-0.7.4.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-659maz3o\creoleparser\setup.py", line 6
        print 'setuptools not installed, using distutils.core'
                                                             ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-659maz3o\creoleparser\
```

**Comment by ThiefMaster** [comment]
I guess the site requires Python 2.

Also, why are you running this as an administrator?

Your question seems to be unrelated to the flask website, too.

**Comment by davidism** [comment]
I don't plan on supporting this site, it's going away soon™ in favor of the Lektor site (https://github.com/pallets/website). Making this app Py2/Py3 compatible and cleaning up the code in general is unfortunately not a good use of my time right now.

In this case it looks like we depend on a library that doesn't support Python 3.

**Comment by zhangsanfu** [comment]
Thanks @davidism

**Comment by nitinnath** [comment]
> Thanks @davidism

have you got solution ???

**Comment by kieryum** [comment]
how to solve problems that the "Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1
\AppData\Local\Temp\pip-install-_f0ajv94\creoleparser\"？
