### ISSUE TITLE
Examples page

### ISSUE THREAD

**Issue by Jonesn11** [pallets/flask-website#73]
On the examples page:
"http://flask.pocoo.org/community/poweredby/" 
many links are dead.
I think this prevents newcomers from being awe-inspired by what one can do with flask.

**Comment by dhyanpatel** [comment]
Can I do this?

**Comment by dhyanpatel** [comment]
Removed some more of the Dead Links
#75

**Comment by davidism** [comment]
Merged, but also this site is no longer in use, so it's sort of moot.
