### ISSUE TITLE
Advocating for the use of Pipenv ?

### ISSUE THREAD

**Issue by jromeem** [pallets/flask-website#80]
I don't know what the pallets team's stance is on Python package managers. I guess it's good to point out that when it comes to application dependency management, the Python Software Foundation officially recommends Pipenv:
https://packaging.python.org/guides/tool-recommendations/#application-dependency-management 

![Screen Shot 2019-05-31 at 1 43 14 PM](https://user-images.githubusercontent.com/1573880/58727477-174b4a80-83aa-11e9-9e52-0731fbd307aa.png)

It would be nice to see popular frameworks like Flask or Django, etc. start advocating it, or at least including it in their quickstart guides! I only discovered it through someone's Flask tutorial.

Anyway, I'm sure you guys have thought about it, but just putting it out there~

**Comment by davidism** [comment]
I don't plan to add recommendations for project management tools at this time. Thanks for asking though!
